version: '3'

services:
  install:
    image: node:10.3-alpine
    working_dir: /project
    volumes:
      - ./:/project
    command: npm install

  rebuild:
    image: node:10.3-alpine
    working_dir: /project
    volumes:
      - ./:/project
    command: npm rebuild node-sass

  test:
    image: node:10.3-alpine
    working_dir: /project
    volumes:
      - ./:/project
    command: npm test

  web:
    image: node:10.3-alpine
    working_dir: /project
    volumes:
      - ./:/project
      - /app/node_modules
    ports:
      - '3030:3030'
    command: npm run start:docker